Arti = [
  "Analitis, memahami, pengetahuan, senang belajar, bermeditasi, penuh kesadaran.",
  "Pemrakarsa, pelopor, pemimpin, bebas, pekerja keras, individualis.",
  "Mudah bekerja sama, beradaptasi, bermitra, memperhatikan orang lain, penengah.",
  "Ekspresif, mudah berbicara, bersosialisasi, seni dan menikmati hidup.",
  "Tingkat spiritual tinggi, intuitif, tercerahkan, idealis, pemimpi.",
  "Mengutamakan prinsip, keteraturan, pelayanan, sulit menerima batasan dan perkembangan yang mapan.",
  "Bertanggung jawab, melindungi, merawat, bermasyarakat, seimbang, simpatik.",
  "Ekspansif, visioner, petualang, menggunakan kebebasan dengan cara konstruktif.",
  "Peduli sesama, dermawan, tidak mementingkan diri sendiri, patuh terhadap kewajiban, ekspresi kreatif."
]

Deskripsi = [
  "Anda orang yang memerlukan tempat dimana anda bisa merasa nyaman dengan yang lain. Anda terlalu menutup diri sehingga seringkali dengan mudah mengalami depresi. Keinginan anda untuk menemukan jawaban-jawaban tersembunyai adalah dengan bantuan supranatural atau hal-hal lain yang tidak disangka karena kepribadian anda yang memang sangat tertutup dan lebih baik tidak berbicara. Perasaan anda tidak terdeteksi oleh orang-orang disekitar karena anda tidak pernah membicarakan tentang diri secara benar. Percakapan anda hanya akan menjadi tidak bernilai. Ketahuilah bahwa anda perlu menjadi diri sendiri dan berusaha menjadi teman yang nyata bagi banyak orang.",
  "Anda mempunyai kepercayaan diri, intelektualitas, dan daya kepemimpinan yang sangat tinggi. Anda juga termasuk orang yang mempunyai pandangan hidup yang luas. Ide-ide kreatif dapat menjadikan anda sebagai pencetus dan penentu suatu kreasi atau tindakan. Cobalah untuk tidak mudah bosan, berubah-ubah pikiran, kehilangan harapan, atau menjadi terlalu agresif dalam menindak-lanjuti hal yang sudah anda mulai atau rintis. Raihlah apa yang menjadi tujuan hidup anda. Anda penyuka petualangan dan hal-hal yang memicu adrenalin. Anda harus mempunyai hobi yang menarik dan menyenangkan. Karena anda mudah bosan, anda tidak menyukai hal-hal yang bersifat monoton dan biasa saja. Hindari emosi, keras kepala, dan mau menang sendiri karena kesuksesan anda terletak pada bagaimana cara anda dapat bersabar dan berdiplomasi dalam meraih apapun tanpa harus bertindak bosy (berlagak seperti bos) atau memaksakan kehendak karena anda sudah mempunyai daya kepemimpinan sejati yang harus diarahkan secara positif.",
  "Anda memerlukan ketentraman, kasih sayang, dan pasangan. Anda rasakan ketiga hal ini dapat melengkapi kehidupan anda. Pikiran anda selalu terpusat pada hal-hal yang positif dan indah. Terkadang bisnis dan hiburan harus dikombinasikan untuk membuat anda lebih bisa mengekspresikan diri dan lebih rileks karena lingkungan tanpa tekanan merupakan keadaan yang anda anggap sangat penting bagi pencapaian dan pengekspresian diri dalam bisnis sekalipun. Anda disarankan untuk tidak terlalu sensitif terhadap hal-hal sepele atau membesar-besarkan hal yang (sepertinya) tidak berguna. Janganlah selalu menaruh rasa curiga pada seseorang. Anda sangat ekspresif dan dapat dengan mudah memenangkan banyak kesempatan bisnis. Anda dapat mencapai kesuksesan hidup melalui dukungan dan bantuan dari orang-orang disekitar. Anda menjadi sangat produktif dan tekun apabila anda sudah mengambil keputusan untuk masuk dalam suatu bisnis tertentu. Anda dapat memenangkan banyak percintaan dimana salah satunya (mungkin) pernah/dapat memberikan kerumitan yang belum pernah terbayangkan.",
  "Anda menularkan banyak kegembiraan dan keceriaan dimanapun anda berada. Kelebihan dari karakter nama ini adalah dapat menghibur semua orang yang kesepian dan bersedih. Anda suka bercerita tentang apapun sedemikian menarik dan mempunyai rasa humor yang tinggi. Anda disarankan untuk benar-benar menentukan karir yang ingin ditekuni sejak awal. Anda tipe orang yang cenderung sangat fleksibel dengan berbagai kondisi sehingga pada akhirnya (terkadang) tidak fokus pada keinginan anda pribadi. Anda bukan orang yang menyukai pekerjaan rutinitas. Daya imajinasi anda dapat mengantar menuju gerbang sukses. Anda akan lebih cocok apabila terlibat dalam karir bidang entertainmen, fashion, travel, public relations atau desain, dimana anda dapat mengekspresikan talenta seni dan komunikasi. Berusahalah sedikit untuk lebih serius dalam memilih pasangan dan jalan hidup anda. Jangan sampai aktivitas-aktivitas yang padat dalam berbagai hal dapat membuat kebingungan dalam memilih apa yang terbaik bagi hidup anda.",
  "Segala talenta adalah milik anda. Anda orang yang yakin dalam apa yang anda lakukan. Akan tetapi anda harus berusaha berjalan pada sisi positif dalam hidup karena kekuatan dari kepribadian itu bisa menjadikan anda orang yang sia-sia. Anda termasuk orang yang cerdas dan sangat pandai. Tidak memakan waktu yang lama bagi anda untuk bisa menguasai banyak hal yang menyangkut karir atau bisnis. Anda dapat meraih sukses besar dalam keuangan. Anda orang yang suka berhubungan dengan orang yang penting yang dapat menguntungkan. Anda terlahir untuk mengajarkan sesuatu hal yang baik untuk kepentingan orang lain.",
  "Anda memerlukan ketentraman, kasih sayang, dan pasangan. Anda rasakan ketiga hal ini dapat melengkapi kehidupan anda. Pikiran anda selalu terpusat pada hal-hal yang positif dan indah. Terkadang bisnis dan hiburan harus dikombinasikan untuk membuat anda lebih bisa mengekspresikan diri dan lebih rileks karena lingkungan tanpa tekanan merupakan keadaan yang anda anggap sangat penting bagi pencapaian dan pengekspresian diri dalam bisnis sekalipun. Anda disarankan untuk tidak terlalu sensitif terhadap hal-hal sepele atau membesar-besarkan hal yang (sepertinya) tidak berguna. Janganlah selalu menaruh rasa curiga pada seseorang. Anda sangat ekspresif dan dapat dengan mudah memenangkan banyak kesempatan bisnis. Anda dapat mencapai kesuksesan hidup melalui dukungan dan bantuan dari orang-orang disekitar. Anda menjadi sangat produktif dan tekun apabila anda sudah mengambil keputusan untuk masuk dalam suatu bisnis tertentu. Anda dapat memenangkan banyak percintaan dimana salah satunya (mungkin) pernah/dapat memberikan kerumitan yang belum pernah terbayangkan.",
  "Anda memerlukan ketentraman, kasih sayang, dan pasangan. Anda rasakan ketiga hal ini dapat melengkapi kehidupan anda. Pikiran anda selalu terpusat pada hal-hal yang positif dan indah. Terkadang bisnis dan hiburan harus dikombinasikan untuk membuat anda lebih bisa mengekspresikan diri dan lebih rileks karena lingkungan tanpa tekanan merupakan keadaan yang anda anggap sangat penting bagi pencapaian dan pengekspresian diri dalam bisnis sekalipun. Anda disarankan untuk tidak terlalu sensitif terhadap hal-hal sepele atau membesar-besarkan hal yang (sepertinya) tidak berguna. Janganlah selalu menaruh rasa curiga pada seseorang. Anda sangat ekspresif dan dapat dengan mudah memenangkan banyak kesempatan bisnis. Anda dapat mencapai kesuksesan hidup melalui dukungan dan bantuan dari orang-orang disekitar. Anda menjadi sangat produktif dan tekun apabila anda sudah mengambil keputusan untuk masuk dalam suatu bisnis tertentu. Anda dapat memenangkan banyak percintaan dimana salah satunya (mungkin) pernah/dapat memberikan kerumitan yang belum pernah terbayangkan.",
  "Anda mempunyai karakter yang unik dan kuat. Tanpa anda sadari, banyak orang akan merasa sopan dan tampil apa adanya. Kegigihan anda dalam meraih kesuksesan karir tidak perlu diragukan lagi. Anda orang yang sangat berambisi untuk maju. Biasanya orang yang berkarakter nama ini adalah orang-orang yang menuju sukses dengan jerih payah mereka sendiri meski tidak ada orang yang membantu dalam perjalanan karir mereka. Akan tetapi, anda tetap menyenangi pekerjaan yang sifatnya rutinitas. Anda orang yang tidak pandai dalam bersosialisasi. Anda orang yang cukup puas dengan kehidupan yang serba menyendiri karena anda ingin mendapatkan keseimbngan antara keramaian dan ketenangan.",
  "Anda orang cukup dipandang dikomunitas anda. Selalu menjadi bahan perhatian. Anda juga selalu menjadi tamu yang paling ditunggu karena aura anda yang memberikan kenyamanan dan keceriaan bagi semua orang. Anda sangat pandai berbicara sehingga anda dianggap sangat menarik oleh banyak orang. Selain itu, ditunjang oleh kepribadian anda yang sangat berwibawa dan praktis dalam menjalankan karir dan usaha sehingga dapat menuju gerbang sukses dengan dukungan teman-teman yang dapat menguntungkan anda. Anda tentunya bukanlah orang yang pasif. Anda bertindak cepat dalam membantu sesama dan sangat peduli terhadap kepentingan masyarakat. Hindari dari aktivitas yang berlebih dengan teman-teman sehingga anda tidak dicap egois oleh pasangan karena terlalu banyak waktu dan usaha yang anda habiskan untuk teman-teman.",
  "Anda tidak pernah mau tinggal diam dalam menjalani hidup. Selalu menemukan diri anda dalam kemajuan karir dan taraf hidup karena kerja keras sendiri. Travel, olahraga, atau petualangan adalah hal yang paling anda sukai. Dari waktu ke waktu, anda selalu merubah penampilan diri dan juga mengubah kepribadian anda kepada sesuatu yang lebih menunjang karir dan kemajuan pribadi. Anda selalu ingin mencari jawaban atas permasalahan dengan melacaknya sendiri. Anda mempunyai bakat menjadi detektif. Jagalah diri agar jangan sampai terlalu terpesona dengan cinta bahkan menjadi budak cinta. Karena anda cenderung menyukai lawan jenis (pasangan) begitu dalam sehingga terkadang tidak dapat menguasai diri anda sendiri. Anda termasuk orang yang agresif dalam menyikapi cinta. Anda juga termasuk orang yang gampang sekali cemburu.",
  "Anda bukan tipe orang yang sombong. Anda menjadi bijaksana melalui berbagai macam pengalaman hidup yang sungguh-sungguh mengajarkan pelajaran untuk lebih mendekatkan diri kepada Tuhan dan berbuat baik bagi semua orang. Itu telah anda sadari betul, sehingga anda merasa tidak perlu untuk berbuat semena-mena atau menyombongkan diri. Anda orang yang sangat romantis dan dapat berkata-kata dengan indah. Anda juga menyukai bahasa dan kultur negara asing. Anda suka memberikan inspirasi kepada banyak orang. Sikap anda yang penuh dengan empati, keceriaan, dan penuh perhatian membuat anda manjadi tamu istimewa dalam setiap undangan. Anda orang yang cukup populer ditengah-tengah teman karena kebaikan yang mereka rasakan. Anda akan jauh lebih sukses apabila berkarir dalam hal-hal kemanusiaan, diplomat, translator, atau petinggi agama. Akan tetapi, apapun karir atau bisis yang anda pilih, itu semua akan berujung pada nilai-nilai kemanusiaan yang anda pegang tinggi karena sikap anda yang dermawan."
]
